export const kContextId = Symbol.for('context.id')
export const kContextInit = Symbol.for('context.init')
export const kHtmlType = Symbol.for('type.html')
export const kElementType = Symbol.for('type.element')
export const kFragmentType = Symbol.for('type.fragment')
export const kCallSiteType = Symbol.for('type.callsite')
export const kJsxPropType = Symbol.for('type.jsxprop')
